### ISSUE TITLE
Improve mobile experience

### ISSUE THREAD

**Issue by liutingdu** [evercam/snapmail#11]
First screenshot:
- [x] Button is not centrally aligned in the sign in page

Second screenshot:
- [x] The hidden loading animation is showing up behind the image
- [x] There is a gap below the image
- [x] Material '+' button doesn't show the '+'
- [x] The delete button disappeared.

Third screenshot:
-  [x] Add some padding around the dialog?

<img src="https://cloud.githubusercontent.com/assets/5046761/14736931/83ea6962-0871-11e6-8a44-7f09ed7b1ac9.jpg" width="300px">
<img src="https://cloud.githubusercontent.com/assets/5046761/14736932/83eaac7e-0871-11e6-977f-87a9a9389b12.jpg" width="300px">
<img src="https://cloud.githubusercontent.com/assets/5046761/14736933/83ecdd96-0871-11e6-82dd-6a0f3e2220ab.jpg" width="300px">

**Comment by affan00** [comment]
done
