### ISSUE TITLE
Design issues on create snapmail form.

### ISSUE THREAD

**Issue by azharmalik3** [evercam/snapmail#16]
![image](https://cloud.githubusercontent.com/assets/6176136/17511449/467da3ac-5e3c-11e6-8f4a-6a7c300cfccc.png)

**Comment by marcoherbst** [comment]
@affan00  , could we bump the priority of this please. Today? Tmrw?

**Comment by affan00** [comment]
I am on it now.

M. Affan Qureshi
Cell No. : +923136007500
Skype: affan_ani

**Comment by affan00** [comment]
It's done
