### ISSUE TITLE
A bunch of errors in one ... Chrome > Inspect > Network

### ISSUE THREAD

**Issue by marcoherbst** [evercam/snapmail#5]
Check out this for an error log :)

![screenshot 2015-12-18 16 23 12](https://cloud.githubusercontent.com/assets/5648894/11901509/de978ee8-a5a3-11e5-97fe-db85739c4a83.png)

**Comment by marcoherbst** [comment]
@azharmalik3  ... @mosic  ... just FYI ... I know you're both busy, but in case you have a flash of light....

**Comment by mosic** [comment]
@marcoherbst It looks like evercam-api is causing problems, multiple queries returned 500 error.

**Comment by azharmalik3** [comment]
Closing this because snapmail front is migrated into dashboard which also resolved these issues.
